### PR TITLE
add Carvalho & Johns-Krull (2023) rotational broadening implementation

### PR DESCRIPTION
**Pull request by chihchunhsu**
new file:   kpicdrp/rotBroadInt.py
	modified:   kpicdrp/wavecal.py
	modified:   kpicdrp/xcorr.py

### CODE REVIEW

**Comment by semaphoreP** [comment]
A couple of style comments: imports should be at the top of the file unless strictly necessary, and relative imports should be done using `import kpicdrp.rotBroadInt as rotBroadInt`.

**Comment by chihchunhsu** [comment]
Sounds good. Changing the style for relative import.

**Comment by semaphoreP** [comment]
Sorry, one more thing: should we remove imports for pyastronomy and remove pyastronomy from the requirements.txt? I don't think it's being used anywhere else.

**Comment by chihchunhsu** [comment]
Sure. There are a couple of PyAstronomy imports in JB's tutorials and analysis code, which I haven't used. Should we also remove all of these?

**Comment by chihchunhsu** [comment]
Remove PyAstronomy dependency and requirements (e3b2480)
and remove jbdrp (ba60547; per the discussion on slack)

**Pull request merged**
